"""Added review_stage column

Revision ID: 16b15afc5327
Revises: bf3468412652
Create Date: 2024-04-25 22:22:18.373747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b15afc5327'
down_revision = 'bf3468412652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_stage', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_session', schema=None) as batch_op:
        batch_op.drop_column('review_stage')

    # ### end Alembic commands ###
