"""Initial migration

Revision ID: bf3468412652
Revises: 
Create Date: 2024-04-24 23:03:57.161489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3468412652'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebook_title', sa.String(length=150), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('review_session', sa.Column('review_stage', sa.String(length=50), nullable=False, server_default='not_reviewed'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_session')
    op.drop_table('user')
    op.drop_column('review_session', 'review_stage')
    # ### end Alembic commands ###
